### ISSUE TITLE
Add Activate() to tray icon OnClick logic

### ISSUE THREAD

**Issue by vadimffe** [HavenDV/H.NotifyIcon#108]
## What would you like to be added:

With following code you can hide your MAUI application once it gets Minimized. Then once clicking on H.NotifyIcon, application icon gets visible in task bar, but it stays hidden. With recent observations Activate() makes application visible. As a request it would be very welcomed to have the same functionality for this library, so that MAUI application on Windows not only appear in Task bar, but also be visible on top of other windows.

```
  Microsoft.Maui.Handlers.WindowHandler.Mapper.AppendToMapping(nameof(IWindow), (handler, view) =>
    {
#if WINDOWS
        var nativeWindow = handler.PlatformView;
        var appWindow = nativeWindow.GetAppWindow();
        if (appWindow is not null)
        {
            appWindow.Changed += (sender, args) =>
            {
                if (appWindow.Presenter is OverlappedPresenter overlappedPresenter)
                {
                    if (args.DidPresenterChange && overlappedPresenter.State == OverlappedPresenterState.Minimized)
                    {
                        appWindow.Hide();
                        Thread.Sleep(5000);
                        nativeWindow.Activate();
                    }
                }
            };
        }

#endif
    });
```

## Why is this needed:

It is a bit not very logical currently that you need to click on icon in tray and then one more time in task bar to get your application window cisible.

## For which Platform:

- [ ] All
- [ ] WPF
- [ ] WinUI
- [ ] Uno
- [ ] Core
- [x] MAUI, Windows

**Comment by vadimffe** [comment]
I am struggling to get it working in my current application. However I remember previously, with above code, it was working. I will create a test project in the upcoming days and share results here.

**Comment by vadimffe** [comment]
I already had one MAUI test project. Added tray icon implementation there. So currently there is some issue as currently while clicking icon in tray, window still stays somehow hidden. It is not behind other windows, but hidden. Only clicking on task bar icon gets window back to visible. Needs to be investigated further.

Test project:
https://github.com/vadimffe/DraggingIssueNetMAUI

Demonstration:
https://github.com/HavenDV/H.NotifyIcon/assets/72302395/e33d14c6-87e8-42f1-bbb2-986fc4917dc8

**Comment by HavenDV** [comment]
Have you tried adding `Thread.Sleep(5000);` before Activate?

**Comment by vadimffe** [comment]
> Have you tried adding `Thread.Sleep(5000);` before Activate?

I think issue is with `Show()`. For me it seems that window stays minimized. It gets visible in task bar, but State is still Minimized. I previously did something similar for bringing windows back from minimized. I think something like this needs to be used in net maui. I will try to test further. 

```
private const int SW_RESTORE = 9;
```

https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-showwindow

**Comment by vadimffe** [comment]
It seems to be working with ShowWindow and SW_RESTORE from link above. Don't know if you want to add it to your library directly. 

I have also noticed that icon stays in the tray even when application is closed. This is probably a topic for new issue.

**Comment by HavenDV** [comment]
> I have also noticed that icon stays in the tray even when application is closed. This is probably a topic for new issue.

Yes, now you need to explicitly call Dispose on TrayIcon to avoid this. For WPF there is a subscription to the Application.Current.Exit event followed by a call to Dispose, but this can never be guaranteed. For MAUI there seems to be something similar

**Comment by HavenDV** [comment]
Both issues will likely be fixed in the latest update. I've also listed you as a co-author, thanks for your research!

**Comment by vadimffe** [comment]
After some recent checks, I can confirm that everything seems to be working now fine with latest version, at least on Windows. This issue can be closed. 

The only thing that I am currently looking for is applying custom themes for context menu. I have not read all the docs yet. Maybe it is there already. 

And thank you for co-authoring, although I haven't done much at all. 

P.S. Also please no emails as text strings in this world of Internet. Trying to stay away from all these crawling spamming bots, don't trust any website for their possible protections.

**Comment by HavenDV** [comment]
I think context menu themes are possible, but I haven't invested in that direction. I think it will be like a development of the WinUI context menu, but I don’t have enough free time yet to do it for free

**Comment by vadimffe** [comment]
Understood, I was checking from the phone, maybe it shows differently. 

Open source is what it is, don't know how supportive is community nowadays. Anyway thank you for what has been done already! I see there are a lot of people looking for tray icon implementation.

I will try to check on the latest topic as well.
