### ISSUE TITLE
Fix nuget repository

### ISSUE THREAD

**Issue by watsug** [HavenDV/H.NotifyIcon#12]
### Describe the bug

There are new versions available for H.NotifyIcon.* but referenced dependency H.NoticyIcon has not been updated accordingly. This results in nuget installation / update failure.

### Steps to reproduce the bug

Try to update e.g. H.NotifyIcon.Wpf nuget to version 2.*

### Screenshots

![obraz](https://user-images.githubusercontent.com/2720485/161607930-65508f52-b38a-4d61-8e37-0b7b0481afdd.png)

### Platform

All

### IDE

Visual Studio 2022

**Comment by HavenDV** [comment]
Thanks. There was a bug in CI that prevented new versions of H.NotifyIcon core package from being published.
