### ISSUE TITLE
i am new in winui3,could you please give us a full example of notifyicon which is a project show me the full use of your project so that i can learn how to use it ,thank you very much

### ISSUE THREAD

**Issue by LanHuangJG** [HavenDV/H.NotifyIcon#125]
## What would you like to be added:
a full example
## Why is this needed:
so that i can learn how to use it 
## For which Platform:
winui
- [ ] All
- [ ] WPF
- [this ] WinUI
- [ ] Uno
- [ ] Core

## Anything else we need to know?

,thank you very much

**Comment by HavenDV** [comment]
Please check https://github.com/HavenDV/H.NotifyIcon/tree/master/src/apps/H.NotifyIcon.Apps.WinUI and https://github.com/HavenDV/H.NotifyIcon/tree/master/src/apps/H.NotifyIcon.Apps.WinUI.Windowless

I will add this to README also and close this issue after
