### ISSUE TITLE
Was support for .NET 6 purposefully removed?

### ISSUE THREAD

**Issue by Timthreetwelve** [HavenDV/H.NotifyIcon#126]
### Describe the bug

Attempting to update the Nuget package from 2.0.118 to 2.0.120 in a .NET 6 WPF application results in a message warning that the .NET framework version was installed.

Nuget package now shows no support for .NET 6 or .NET 7.

Wondering if this is by design. I have every intention to update the project to .NET 8 but am not ready to do so now since support for .NET 6 doesn't expire until November 12, 2024.

Please advise.

### Screenshots

![devenv_2023-12-01_22-13-01](https://github.com/HavenDV/H.NotifyIcon/assets/43152358/7114b10d-a3f8-4543-bcdf-225b5e72452b)

![msedge_2023-12-01_21-59-36](https://github.com/HavenDV/H.NotifyIcon/assets/43152358/045a885e-4f95-4c45-8eee-ec2d6956bd30)

### NuGet package version

2.0.122

### Platform

WPF

### IDE

Visual Studio 2022

### Windows Version

Windows 11

### WindowsAppSDK Type

None

**Comment by HavenDV** [comment]
I agree with you, I checked the net 6/net 7 support dates and returned this.

**Comment by Timthreetwelve** [comment]
Thank you!
