### ISSUE TITLE
Creating a TaskbarIcon in-code causes windows to treat each instance as unique

### ISSUE THREAD

**Issue by kurmachu** [HavenDV/H.NotifyIcon#13]
### Describe the bug

I may be doing something incorrectly, if so feel free to correct me.

I'm creating a new `TaskbarIcon` in-code by using
```cs
taskbarIcon = new TaskbarIcon();
taskbarIcon.Icon = new System.Drawing.Icon("Assets/(The icon)");
taskbarIcon.ToolTipText = "(tooltip name)";
```

But this creates a new "unique" icon every time, which floods settings and doesn't let the user choose if the icon should be in the overflow menu or not.

### Steps to reproduce the bug

1. Create a `TaskbarIcon` manually, using the code described above
2. Launch the app multiple times
3. Check "Other system tray icons" in settings

### Expected behavior

Only one entry for the application 

### Screenshots

![image](https://user-images.githubusercontent.com/31492625/162061064-282c9597-839e-41fb-aa2a-cb6feeb4c33f.png)

### NuGet package version

`2.0.24`

### Platform

WinUI

### IDE

Visual Studio 2022

### Additional context

I may be doing something wrong, or creating a `TaskbarIcon` in-code may be fully unsupported.

It is quite possible there's simply some ID property or something I'm not aware I need to set.

**Comment by kurmachu** [comment]
Just tried to make one in xaml, and it seems the result is the same, so perhaps it _always_ makes a new instance?
```xaml
<h:TaskbarIcon
    x:Key="taskbarIcon"
    ToolTipText="(the text)" />
```
```cs
taskbarIcon = (TaskbarIcon)Resources["taskbarIcon"];
taskbarIcon.Icon = new System.Drawing.Icon("Assets/(the icon)");
```

**Comment by HavenDV** [comment]
Yes, I confirm the problem, it is quite critical, in the process of being fixed.

**Comment by kurmachu** [comment]
This is great to hear! Thank you so much for the quick response. Do you know if a `TaskbarIcon` implemented fully in code will support the fix?

**Comment by HavenDV** [comment]
Yes of course. The main problem I want to solve is so that the user does not have to set a fixed GUID on a permanent basis (but with such an option if necessary). I need to check if `Assembly.GetEntryAssembly()` returns the same Guid for the same application and different for different applications so that I can use this as the default behavior.

**Comment by HavenDV** [comment]
> Just tried to make one in xaml, and it seems the result is the same, so perhaps it _always_ makes a new instance?
> 
> ```
> <h:TaskbarIcon
>     x:Key="taskbarIcon"
>     ToolTipText="(the text)" />
> ```
> 
> ```cs
> taskbarIcon = (TaskbarIcon)Resources["taskbarIcon"];
> taskbarIcon.Icon = new System.Drawing.Icon("Assets/(the icon)");
> ```

I want to note that you can use initialization from xaml, like this:
```xml
<tb:TaskbarIcon IconSource="ms-appx:///Assets/Red.ico"/>
```

**Comment by HavenDV** [comment]
A fix for this issue should be available in a few minutes. TrayIcon.Id will now be determined by default based on the hash of the entry assembly simple name. For the second or more icons in the application, you will need to specify an explicit Id.

**Comment by kurmachu** [comment]
Thank you for the quick fix, I've updated to the latest NuGet package, but it seems now an icon will not show. I'm setting id like this: 
```cs
taskbarIcon.Id = new System.Guid("16b7613a-492e-4cfe-a94c-1ad37df2d464");
```
Am I required to do this in xaml for it to properly be set up? I couldn't figure out how to specify a GUID in it. Should I set up a new issue for this?

Icon continues to not display when not setting an id, and just for clarification I mean the whole concept of a `TaskbarIcon`, not simply the image it displays.

**Comment by kurmachu** [comment]
I think I'm setting id with a binding correctly now? The icon continues to not display.
```xaml
<h:TaskbarIcon
    x:Key="taskbarIcon"
    ToolTipText="(the title)"
    Id="{Binding Path=taskbarGuid}"
    />
```
```cs
System.Guid taskbarGuid = new System.Guid("16b7613a-492e-4cfe-a94c-1ad37df2d464");
```

**Comment by HavenDV** [comment]
Setting the Id is definitely not needed unless you are using multiple TaskbarIcons within the same application.
I think it has to do with changes in initialization. Previously TrayIcon was created in the TaskbarIcon constructor, now it is created after the Loaded event. As a consequence, if your TaskbarIcon is stored in resources and you have a Windowless application, you need to explicitly call `TryForceCreate`:
<img width="597" alt="image" src="https://user-images.githubusercontent.com/3002068/162525134-9418d7b5-ae7c-4242-87de-a5ff69218940.png">

**Comment by HavenDV** [comment]
The advantage of this change will be the acceleration of application loading, because previously, due to the fact that the initialization process took place in the constructor, it was necessary to make requests to WinAPI every time a property was changed. Right now this happens in a single request after the Loaded event.

**Comment by kurmachu** [comment]
Can confirm this works! Thank you so much! Your library is a lifesaver.

_For some reason Windows 11 doesn't actually realize a new icon has been added (when an icon is set to not go to the overflow tray) until you open another icon (like task manager, which makes both of them show up) but I don't think that is related to this library._

**Comment by HavenDV** [comment]
Sounds like a different problem, can you describe it in more detail and attach screenshots or videos?

**Comment by kurmachu** [comment]
I still don't think this is your problem, but here's what happens once you open task manager (or any other application that adds an icon)

https://user-images.githubusercontent.com/31492625/162528894-1dffe76e-4a46-485f-9ce6-8c53f5706215.mp4

This does not happen in the overflow up arrow tray thing, in which case it works fine. I do not know if this is a change in the latest version, as due to the changing guids, all icons would go to the overflow tray.

 `Windows 11 22H2 (OS Build 22593.1)` (Current insiders beta)

**Comment by HavenDV** [comment]
I have not tested this case. Thank you. I'm also on the latest beta build of Windows 11

**Comment by HavenDV** [comment]
I can confirm this behavior myself.
I also checked hardcodet notifyicon they are having the same problem too.
I still haven't found a workaround for this.

**Comment by kurmachu** [comment]
This may also be a Windows 11 bug which Microsoft needs to fix.

I recommend making another issue to track this if you would like; you may feel free to use my recording in it if you do so.

**Comment by HavenDV** [comment]
I created a separate issue for this. I also solved this problem, but I'll leave it open in order to find a better solution if possible.
