### ISSUE TITLE
Add option for a fixed GUID to TaskbarIcon

### ISSUE THREAD

**Issue by mindaugasveblauskas** [HavenDV/H.NotifyIcon#138]
## What would you like to be added:

Add option for a fixed GUID to TaskbarIcon.

## Why is this needed:

Currently, TaskbarIcon has only the default constructor which creates TrayIcon using default constructor as well, which then uses CreateUniqueGuidForProcessPath and generates a different GUID for binaries in different paths. For an app, which has multiple versions side-by-side that's a problem. Even if you have your binaries signed with EV code signing certificate (which according to Microsoft should keep tray icon settings when updating the app), you still can't use a fixed GUID with the current implementation.

I did some testing with a fixed GUID and after using different binary paths, the tray icon settings were kept (I've moved the tray icon to the taskbar area from a hidden place where all the icons are stored). And after launching the app with a binary in a different path, the tray icon was still in the taskbar where I moved it before.

## For which Platform:

- [ ] All
- [ ] WPF
- [X] WinUI
- [ ] Uno
- [ ] Core

**Comment by HavenDV** [comment]
Hi. Please try using TaskbarIcon.Id dependency property and post here if it does not work.
<img width="1179" alt="image" src="https://github.com/HavenDV/H.NotifyIcon/assets/3002068/f6752f8b-a66f-435a-bc6d-b733eccf636f">

Usually this property for second icon but it can work for your case.

**Comment by mindaugasveblauskas** [comment]
It works when launching the app via visual studio as unpackaged app, but the app crashes when published as self-contained app. Event viewer logs does not provide any useful info.

**Comment by HavenDV** [comment]
Can you try TrayIcon class from core library instead TaskbarIcon xaml wrapper?

**Comment by mindaugasveblauskas** [comment]
Sorry, but apparently your initial suggestion seems to be working properly both on visual studio as unpackaged app and when installed as self-contained app. Thank you!
