### ISSUE TITLE
Pinned TrayIcons are not displayed until another TrayIcon appears

### ISSUE THREAD

**Issue by HavenDV** [HavenDV/H.NotifyIcon#14]
### Describe the bug

For some reason Windows 11 doesn't actually realize a new icon has been added (when an icon is set to not go to the overflow tray) until you open another icon (like task manager, which makes both of them show up) but I don't think that is related to this library.
This may also be a Windows 11 bug which Microsoft needs to fix.

### Steps to reproduce the bug

I still don't think this is your problem, but here's what happens once you open task manager (or any other application that adds an icon)

https://user-images.githubusercontent.com/31492625/162528894-1dffe76e-4a46-485f-9ce6-8c53f5706215.mp4

This does not happen in the overflow up arrow tray thing, in which case it works fine. I do not know if this is a change in the latest version, as due to the changing guids, all icons would go to the overflow tray.

### Platform

All

### Additional context

`Windows 11 22H2 (OS Build 22593.1)` (Current insiders beta)
Based on conversation in https://github.com/HavenDV/H.NotifyIcon/issues/13

**Comment by HavenDV** [comment]
I can confirm this behavior myself.
I also checked hardcodet notifyicon they are having the same problem too.
I still haven't found a workaround for this.

There is an idea to send an event explicitly to the Tray window that reloads it or simulates adding another TrayIcon

**Comment by HavenDV** [comment]
Added a workaround through creating and deleting an empty icon with a fixed ID after adding the icon to the tray.

**Comment by kurmachu** [comment]
> Added a workaround through creating and deleting an empty icon with a fixed ID after adding the icon to the tray.

Would this not possibly add an unintended entry to the "Other system tray icons" section of settings?

**Comment by HavenDV** [comment]
It will add, but it will be the only one for all applications using this library. So far I haven't found a way to do this without adding a new icon. I tried various manipulations like removing adding hiding display after initialization

**Comment by kurmachu** [comment]
So Microsoft pushed an update recently, and this caught my eye:
![image](https://user-images.githubusercontent.com/31492625/163488408-a4f77df4-018d-4594-b5bc-ac6a77b3594c.png)

I'm still on `2.0.25`, and it seems that the icon is working correctly now. Perhaps Microsoft fixed this? Can you confirm if it's working for you?

**Comment by HavenDV** [comment]
Yes, I checked and confirm that the problem is gone. The only point is that it is not known which version range is affected. But I released an update where I disabled workaround with the creation of an additional icon.
The current version of Windows where the problem disappears is 22598.1
