### ISSUE TITLE
Wrong background in tray context menu in win 10

### ISSUE THREAD

**Issue by m1adow** [HavenDV/H.NotifyIcon#145]
### Describe the bug

Hi! I'm using your library to add a tray functionality to my app. But I encountered a bug. On Windows 10, the tray context menu has a background color that differs from the window one. How do you think I could fix it?

### Steps to reproduce the bug

1. Set light theme in windows
2. Set ContextMenuMode to SecondWindow
3. Run the app
4. Set a dark theme in the app
5. Open the context tray menu

### Expected behavior

Background colors are equal

### Screenshots

![image](https://github.com/HavenDV/H.NotifyIcon/assets/84251113/dfe553b5-c68b-41f4-bd9e-0b5bb87be6e4)

### NuGet package version

H.NotifyIcon.WinUI 2.0.124

### Platform

WinUI

### IDE

Visual Studio 2022

### Windows Version

Windows 10

### WindowsAppSDK Version

1.0

### WindowsAppSDK Type

Packaged

**Comment by HavenDV** [comment]
Hi. Thank you for raising the issue. Since the development of this, a whole series of new versions of WindowsAppSdk have been released, and I think I need to fix this for the current version
What is version of WindowsAppSDK you use now?

**Comment by HavenDV** [comment]
@Khiro95 Very useful feedback, thank you very much, I'll commit it now. But you can also provide single line PR if you want

**Comment by Khiro95** [comment]
> @Khiro95 Very useful feedback, thank you very much, I'll commit it now. But you can also provide single line PR if you want

@HavenDV You are welcome. I will open a PR and let you review it.
