### ISSUE TITLE
ToolTipText doesn't work from 2.0.25

### ISSUE THREAD

**Issue by ArvinZJC** [HavenDV/H.NotifyIcon#16]
### Describe the bug

The tray icon shows the tooltip text properly in 2.0.24, but no tooltip is shown from 2.0.25.

### Steps to reproduce the bug

``` XAML
<tb:TaskbarIcon
    LeftClickCommand="{x:Bind CommandsViewModel.ToggleMainWindowVisibilityCommand}"
    IconSource="ms-appx:///Assets/AppIcon/AppIcon.ico"
    MenuActivation="RightClick"
    NoLeftClickDelay="True"
    ToolTipText="Test">
    <tb:TaskbarIcon.ContextFlyout>
        <MenuFlyout>
            <MenuFlyoutItem
                Text="Settings" />
            <MenuFlyoutSeparator />
            <MenuFlyoutItem
                Text="Exit" />
        </MenuFlyout>
    </tb:TaskbarIcon.ContextFlyout>
</tb:TaskbarIcon>
```

### Expected behavior

The tray icon's tooltip text should be shown as previous in 2.0.24.

### NuGet package version

>= 2.0.25

### Platform

WinUI

### IDE

Visual Studio 2022

### Additional context

WinUI 3 from Windows App SDK 1.0

**Comment by HavenDV** [comment]
Thank you, this has been fixed. The update should be available in a few minutes.
