### ISSUE TITLE
Can H.NotifyIcon use in NET8?

### ISSUE THREAD

**Issue by KILLMILEDC** [HavenDV/H.NotifyIcon#165]

**Comment by KILLMILEDC** [comment]
Severity	Code	Description	Project	File	Line	Suppression State	Details
Warning (active)	NU1701	Package '32feet.NET 3.5.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net6.0-windows7.0'. This package may not be fully compatible with your project.

**Comment by HavenDV** [comment]
Do you mean net6? WinUI supports only net8, but WPF supports both net6/net8
