### ISSUE TITLE
Throw "TryCreate Failed" exception message

### ISSUE THREAD

**Issue by wf-soft** [HavenDV/H.NotifyIcon#17]

**Comment by HavenDV** [comment]
I'm sorry, without context, this exception means absolutely nothing. Previously it was ignored, I included it in new versions to remove errors in rare cases like yours, but context is needed.

**Comment by HavenDV** [comment]
Unfortunately, the Win32 API for NotifyIcon does not return an error description if something goes wrong. So the context is needed https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shell_notifyicona#return-value

**Comment by HavenDV** [comment]
Please test this with version 2.0.45
