### ISSUE TITLE
Notify icon disappear when explorer.exe restart

### ISSUE THREAD

**Issue by jesse51076008** [HavenDV/H.NotifyIcon#22]
### Describe the bug

Notify icon disappear when explorer.exe restart

**Comment by HavenDV** [comment]
Fixed in https://github.com/HavenDV/H.NotifyIcon/commit/dffadd33e6c173539c7bd0d268a78a7ac893a75c

**Comment by JasonWei512** [comment]
I am having the exact same issue on Windows 11 (both the GDI system tray in stable builds and the new XAML system tray in Insider Release Preview channel).
I am using `2.0.86` in a console program.
