### ISSUE TITLE
Context menu wrong height

### ISSUE THREAD

**Issue by IllyaTheHath** [HavenDV/H.NotifyIcon#26]
### Describe the bug

The height of the context menu is not calculated correctly in SecondWindow mode, tried with multi language and font family/size, and it shows a scorll bar.
Sometimes it won't  shown, just a little white empty box.

### Steps to reproduce the bug

```
var settingMenuItem = new MenuFlyoutItem()
{
    Icon = new SymbolIcon(Symbol.Setting),
    Text = I18N["TrayIcon.Main"],
    // ToolTip = I18N["TrayIcon.Main.Tooltip"]
};
var exitMenuItem = new MenuFlyoutItem()
{
    Icon = new SymbolIcon(Symbol.Cancel),
    Text = I18NSource.Instance["TrayIcon.Exit"],
    // ToolTip = I18N["TrayIcon.Exit.Tooltip"]
};

var contextMenu = new MenuFlyout();
contextMenu.Items.Add(settingMenuItem);
contextMenu.Items.Add(exitMenuItem);

_taskbarIcon = new();
_taskbarIcon.ContextFlyout = contextMenu;
_taskbarIcon.IconSource = iconBitmap;
_taskbarIcon.ContextMenuMode = ContextMenuMode.SecondWindow;

if (!_taskbarIcon.IsCreated)
{
    _taskbarIcon.ForceCreate();
}
```

### Expected behavior

Menu height is correct and do not show the scroll bar

### Screenshots

![image](https://user-images.githubusercontent.com/22436811/174248404-0b19a454-82e6-4b2f-9aa1-a7609d8def47.png)
![en](https://user-images.githubusercontent.com/22436811/174246208-2d1c6287-9216-4c25-9a3c-efdea8b4a8f8.png)
![ch](https://user-images.githubusercontent.com/22436811/174246247-7d136724-88a6-4035-816b-2ed10e9e46d9.png)
![en2](https://user-images.githubusercontent.com/22436811/174247533-04dc3623-e602-4561-be7f-17df40610eb4.png)

### NuGet package version

H.NotifyIcon.WinUI 2.0.50

### Platform

WinUI

### IDE

Visual Studio 2022

### Windows Version

Windows 10

### Additional context

net6.0-windows10.0.22000.0

**Comment by HavenDV** [comment]
Thanks for the problem. This has already been discussed [here](https://github.com/HavenDV/H.NotifyIcon/issues/21). At the moment I do not know how to solve this problem, but I did not try to test this on WindowsAppSDK 1.1

**Comment by HavenDV** [comment]
I have released a new version with updated window size calculations (thanks to @l619534951) but wrong sizes still pop up in some cases. I would appreciate any help in testing and repeatable sequences of actions when incorrect sizes appear.
Please post any questions about this issue in https://github.com/HavenDV/H.NotifyIcon/issues/21
