### ISSUE TITLE
[SecondWindow Mode] Context menu theme not change when App Theme change.

### ISSUE THREAD

**Issue by l619534951** [HavenDV/H.NotifyIcon#27]
### Describe the bug

if change app theme from app (not from system setting ), the context menu window's theme is not change.

### Steps to reproduce the bug

1. change theme from app.
2. context menu(SecondWindow mode) theme not change.

### Expected behavior

context menu window's theme should change when app theme change.
> **current:** context menu window's theme only change when system theme change.

### Screenshots

![image](https://user-images.githubusercontent.com/17621099/180178076-ff187542-ea10-4bad-856f-7b6352740dd9.png)
![image](https://user-images.githubusercontent.com/17621099/180178176-3afaaef8-4f64-4aaa-9589-af5374e82613.png)

### NuGet package version

2.0.56

### Platform

WinUI

### IDE

Visual Studio 2022

### Windows Version

Windows 11

### WindowsAppSDK Version

1.1

**Comment by l619534951** [comment]
had fixed in NuGet package version: 2.0.57

**Comment by HavenDV** [comment]
Thanks for the issue and quick PR for it!
