### ISSUE TITLE
[Question] Custom TrayIcon Id when using TaskbarIcon

### ISSUE THREAD

**Issue by Ryochan7** [HavenDV/H.NotifyIcon#29]
The source code for TaskbarIcon.Properties.cs seems to imply that the Id dependency property can be used to edit the Id that is used by the stored TrayIcon instance. However, the OnIdChanged method does not update the Id property of the TrayIcon instance but only the Id value stored in TaskbarIcon. The TaskbarIcon Id seems to usually be an empty Guid anyway. I was wondering what the intended purpose of that dependency property is supposed to be and if the current behavior should change.

```
[DependencyProperty<Guid>("Id",
    Description = "Gets or sets the TrayIcon Id. Use this for second TrayIcon in same app.", Category = CategoryName)]
````

https://github.com/HavenDV/H.NotifyIcon/blob/master/src/libs/H.NotifyIcon.Shared/TaskbarIcon.Properties.cs#L3

I am running into an edge case where it might be useful to be able to explicitly set the Guid Id used by the stored TrayIcon instance before the TrayIcon.Create method is called. Currently using H.NotifyIcon in the app DS4Windows. When using DS4Windows normally, everything works fine. However, there is an edge case in the app where DS4Windows copies the DS4Windows.exe executable to a different file location with a different name (Custom Exe Name setting) to get around DS4 emulation blocks put in place by the Steam Input API; the Steam client will implicitly disable DS4 input controller support if the client detects either DS4Windows.exe or InputMapper.exe running on a system. Running DS4Windows with a different executable filename works around the block and the original assembly DLL DS4Windows.dll will be loaded by the executable.

Using the hashed assembly location for the generated Guid makes the TrayIcon.Create method fail in that case. Being able to set an explicit Guid seems to work around the problem and allow the weird DS4Windows workaround to function as intended.

Running Windows 10 Pro 19044.1826
.NET 6.0.7

Reference issue:
https://github.com/Ryochan7/DS4Windows/issues/2484

**Comment by HavenDV** [comment]
I have released a new version with corrected work of Id/CustomName properties. I recommend trying CustomName="Second" first, and only if that doesn't work, use an explicit Id setting.

The hashing was done because Windows stores settings for an icon according to the location of the binary that controls it.
https://docs.microsoft.com/en-us/windows/win32/api/shellapi/ns-shellapi-notifyicondataa#troubleshooting

**Comment by Ryochan7** [comment]
Ended up learning about the implications of the shared GUID with the Shell_NotifyIcon Windows call. Adding a postfix string with the executable file name was enough to work around the issue while testing.

Thank you for the change. Looks like editing CustomName would do the trick and allow the edge case to work. I'll check it out a bit later.
