### ISSUE TITLE
Separate WPF parts

### ISSUE THREAD

**Issue by dotMorten** [HavenDV/H.NotifyIcon#3]
Nice work!

Have you considered splitting this library into two parts: One for creating icons regardless of UI framework, with just generic classes, and an extension that adds the WPF piece.

The reason for that is reusing the trayicon creation in other UI frameworks, like services, WinUI3 etc. I was able to reuse your interop code and re-write the trayicon class a bit to just create the icon, without using any WPF types, and have it work with WinUI3.
But if you just had the core classes in its own package, I could create a WinUI extension that's equivalent to the WPF bits, but reusing all the awesome interop work you've done.

**Comment by HavenDV** [comment]
Done: https://www.nuget.org/packages/H.NotifyIcon/

**Comment by dotMorten** [comment]
Holy crap! That is INSANELY fast!

**Comment by dotMorten** [comment]
I was thinking about taking it one step further. The TaskBarIcon has quite a lot of good reusable functionality.
My thinking was a more basic TaskBarIcon class that doesn't use the WPF and WinForms classes, but operates more on hwnds, and raw interop data, and then WPF builds on top of that and adds the WPF specific stuff to it. That way one doesn't have to rebuild all the message sing, icon data, click timers, events etc once again.

**Comment by HavenDV** [comment]
https://github.com/dotMorten/WinUIEx/blob/main/docs/concepts/TrayIcon.md
Good job. I want to add H.NotifyIcon.WinUI package based on H.NotifyIcon. Do you mind if I follow your code at some point?

**Comment by dotMorten** [comment]
Of course! I do have plans to rewrite it some and get rid of the message sink and rely on my more generic message monitor

**Comment by HavenDV** [comment]
> I was thinking about taking it one step further. The TaskBarIcon has quite a lot of good reusable functionality.
> My thinking was a more basic TaskBarIcon class that doesn't use the WPF and WinForms classes, but operates more on hwnds, and raw interop data, and then WPF builds on top of that and adds the WPF specific stuff to it. That way one doesn't have to rebuild all the message sink, icon data, click timers, events etc once again.

Finally, after more than a year, I will finally add it soon. This can also be used in console applications.
