### ISSUE TITLE
Strange menu position and width

### ISSUE THREAD

**Issue by LeSnow-Ye** [HavenDV/H.NotifyIcon#30]
### Describe the bug

The menu would appear at the top of the screen on first right-click

More right-clicks would take it to the right position, but the width of it is still strange unless manually set it

---
And it seems that the menu has a poor performance (a little bit lag, low animation fps, relatively high cpu usage)

### Screenshots

The menu would appear at the top of the screen on first right-click
![图片](https://user-images.githubusercontent.com/40481418/182293043-49201a70-3b87-434d-9f95-cd8f7bed72d2.png)

---

More right-clicks would take it to the right position, but the width of it is still strange unless manually set it
![图片](https://user-images.githubusercontent.com/40481418/182293032-00e4000b-0b57-4f78-8c62-24a4a658d0c9.png)

---

![图片](https://user-images.githubusercontent.com/40481418/182296344-c284cb5d-e3cf-483a-8152-7a158d7be777.png)

### NuGet package version

H.NotifyIcon.Wpf 2.0.59

### Platform

WPF

### IDE

Visual Studio 2022

### Windows Version

Windows 11

### Additional context

Code for H.NotifyIcon
```xml
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:tb="http://www.hardcodet.net/taskbar"
    xmlns:vm="clr-namespace:Leanode.ViewModels">
    <tb:TaskbarIcon
        x:Key="NotifyIcon"
        IconSource="/Resources/Logo.ico"
        LeftClickCommand="{Binding ShowWindowCommand}"
        NoLeftClickDelay="True"
        ToolTipText="Left-click to show window, right-click for menu">
        <tb:TaskbarIcon.DataContext>
            <vm:NotifyIconViewModel />
        </tb:TaskbarIcon.DataContext>
        <tb:TaskbarIcon.ContextMenu>
            <ContextMenu ItemsSource="{Binding MenuItems}">
                <ContextMenu.ItemTemplate>
                    <DataTemplate DataType="MenuItem">
                        <MenuItem Command="{Binding Command}" Header="{Binding Text}" />
                    </DataTemplate>
                </ContextMenu.ItemTemplate>
            </ContextMenu>
        </tb:TaskbarIcon.ContextMenu>
    </tb:TaskbarIcon>
</ResourceDictionary>
```

```csharp
using System.Windows;
using H.NotifyIcon;

namespace Leanode
{
    /// <summary>
    /// Interaction logic for App.xaml
    /// </summary>
    public partial class App : Application
    {
        private TaskbarIcon? _notifyIcon;

        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);
            
            _notifyIcon = (TaskbarIcon)TryFindResource("NotifyIcon");   
            _notifyIcon.ForceCreate();
        }

        protected override void OnExit(ExitEventArgs e)
        {
            _notifyIcon?.Dispose();
            base.OnExit(e);
        }
    }
}

```

Meanwhile, I'm using MaterialDesignThemes.

**Comment by HavenDV** [comment]
I was unable to confirm the issue using MaterialDesignThemes 4.5 and code like this on top of [the test application H.NotifyIcon.Apps.Wpf.Windowless](https://github.com/HavenDV/H.NotifyIcon/tree/master/src/apps/H.NotifyIcon.Apps.Wpf.Windowless):
```xml
<ResourceDictionary>
  <ResourceDictionary.MergedDictionaries>
      <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Dark.xaml" />
      <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
      <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.Blue.xaml" />
      <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Red.xaml" />
      <ResourceDictionary Source="NotifyIconResources.xaml" />
  </ResourceDictionary.MergedDictionaries>
</ResourceDictionary>
```
First of all, you should try the original https://www.nuget.org/packages/Hardcodet.NotifyIcon.Wpf
Perhaps the problem will not recur in it, I will understand the differences, and you will have a quick solution.

**Comment by LeSnow-Ye** [comment]
> 

I tried https://www.nuget.org/packages/Hardcodet.NotifyIcon.Wpf just now. The menu became smooth, while the problem of position and width was still there. Then I find that getting rid of ItemTemplate solved this. 

Now everything is fine, thanks a lot

**Comment by HavenDV** [comment]
Thank you. Ideally, I'd like to ask you to check my package without the ItemTemplate to see if that's what's causing the width and performance issues.

**Comment by LeSnow-Ye** [comment]
> Thank you. Ideally, I'd like to ask you to check my package without the ItemTemplate to see if that's what's causing the width and performance issues.

Yes it is. Now the menu is quite fine.
I suppose I wrote some bugs.😅

**Comment by HavenDV** [comment]
Try to use two static resources for ContextMenu and for ContextMenu.ItemTemplate:
```xml
    <DataTemplate
        x:Key="ItemTemplate"
        DataType="MenuItem">
       <MenuItem Command="{Binding Command}" Header="{Binding Text}" />
    </DataTemplate>
    <ContextMenu
        x:Key="ContextMenu"
        ItemsSource="{Binding MenuItems}"
        ItemTemplate="{StaticResource ItemTemplate}"
        />
    <tb:TaskbarIcon
        x:Key="NotifyIcon"
        IconSource="/Resources/Logo.ico"
        LeftClickCommand="{Binding ShowWindowCommand}"
        NoLeftClickDelay="True"
        ToolTipText="Left-click to show window, right-click for menu"
        ContextMenu="{StaticResource ContextMenu}"
        >
        <tb:TaskbarIcon.DataContext>
            <vm:NotifyIconViewModel />
        </tb:TaskbarIcon.DataContext>
    </tb:TaskbarIcon>
```
