### ISSUE TITLE
WinUI 3 Unpackaged app crashed when open the context menu

### ISSUE THREAD

**Issue by xiaoli8848** [HavenDV/H.NotifyIcon#37]
### Describe the bug

My WinUI 3 Unpackaged app crashed when i right clicked on the tray icon.

I did not add a icon file, but i think it doesn't matter, because the sample works perfectly after i delete its icon file and related statements in xaml code.

There wasn't any exception message shown after the crash. The only message i got is the exit code : 3221226107 (0xc000027b).

### Steps to reproduce the bug

1. Install the NuGet package.
2. Add these codes:
In MainWindow.xaml
``` xaml
<Window xmlns:controls="using:AutoDL.Controls">
    <Grid>
        <!--Other Codes-->
        <controls:TrayIconContextMenu/>
    </Grid>
</Window>
```
In TrayIconContextMenu.xaml
``` xaml
<UserControl
    x:Class="AutoDL.Controls.TrayIconContextMenu"
    xmlns:tb="using:H.NotifyIcon">

    <UserControl.Resources>
        <XamlUICommand
            x:Key="ShowHideWindowCommand"
            ExecuteRequested="ShowHideWindowCommand_ExecuteRequested"
            Label="Show/Hide Window"
            Description="Show/Hide Window">
            <XamlUICommand.IconSource>
                <SymbolIconSource Symbol="OpenPane"/>
            </XamlUICommand.IconSource>
            <XamlUICommand.KeyboardAccelerators>
                <KeyboardAccelerator
                    Key="S"
                    Modifiers="Control"
                />
            </XamlUICommand.KeyboardAccelerators>
        </XamlUICommand>
        <XamlUICommand
            x:Key="ExitApplicationCommand"
            ExecuteRequested="ExitApplicationCommand_ExecuteRequested"
            Label="Exit"
            Description="Exit">
            <XamlUICommand.IconSource>
                <SymbolIconSource Symbol="ClosePane" />
            </XamlUICommand.IconSource>
            <XamlUICommand.KeyboardAccelerators>
                <KeyboardAccelerator
                    Key="E"
                    Modifiers="Control"
                />
            </XamlUICommand.KeyboardAccelerators>
        </XamlUICommand>
        <MenuFlyout
            x:Key="TrayContextFlyout"
            AreOpenCloseAnimationsEnabled="False">
            <MenuFlyoutItem Command="{StaticResource ShowHideWindowCommand}" />
            <MenuFlyoutSeparator />
            <MenuFlyoutItem Command="{StaticResource ExitApplicationCommand}" />
        </MenuFlyout>
    </UserControl.Resources>

    <tb:TaskbarIcon
        x:Name="TrayIcon"
        ToolTipText="AutoDL"
        ContextFlyout="{StaticResource TrayContextFlyout}"
        NoLeftClickDelay="True"
        ContextMenuMode="SecondWindow"
        LeftClickCommand="{StaticResource ShowHideWindowCommand}"
    />
</UserControl>
```
In TrayIconContextMenu.cs
``` csharp
public sealed partial class TrayIconContextMenu : UserControl
    {
        public TrayIconContextMenu()
        {
            this.InitializeComponent();
        }

        public void ShowHideWindowCommand_ExecuteRequested(object? _, ExecuteRequestedEventArgs args)
        {
            var window = UIHelper.MainWindow;
            if (window == null)
            {
                return;
            }

            if (window.Visible)
            {
                window.Hide();
            }
            else
            {
                window.Show();
            }
        }

        public void ExitApplicationCommand_ExecuteRequested(object? _, ExecuteRequestedEventArgs args)
        {
            TrayIcon.Dispose();
            UIHelper.MainWindow.Close();
        }
    }
```
3. Run the app.
4. Right click on the tray icon.

### Expected behavior

It should show a fluent design context menu after i right clicked it.

### NuGet package version

2.0.64

### Platform

WinUI

### IDE

Visual Studio 2022

### Windows Version

Windows 11

### WindowsAppSDK Version

1.1

### WindowsAppSDK Type

Unpackaged

**Comment by xiaoli8848** [comment]
Now I know the reason for this exception.
My app calls utility class code on the Activated event to **set the app background to the Mica material**. After I delete the relevant code, the menu will appear normally after right-clicking the tray icon.
These are the relevant codes:
``` csharp
using System.Runtime.InteropServices;
using Windows.System;
using Microsoft.UI;
using Microsoft.UI.Composition;
using Microsoft.UI.Composition.SystemBackdrops;
using Microsoft.UI.Windowing;
using WinRT;
using WinRT.Interop;

namespace AutoDL.Utilities;

public static class UIHelper
{
    public const int ICON_BIG = 1;
    public const int ICON_SMALL = 0;
    public const int WA_ACTIVE = 0x01;
    public const int WA_INACTIVE = 0x00;
    public const int WM_ACTIVATE = 0x0006;
    public const int WM_SETICON = 0x0080;

    private static WindowsSystemDispatcherQueueHelper m_wsdqHelper; // See separate sample below for implementation
    private static MicaController m_micaController;
    private static SystemBackdropConfiguration m_configurationSource;

    public static IntPtr MainWindow_Handle = WindowNative.GetWindowHandle(MainWindow);

    public static WindowId MainWindow_ID = Win32Interop.GetWindowIdFromWindow(MainWindow_Handle);

    public static MainWindow MainWindow => (MainWindow)(Application.Current as App).m_window;

    public static AppWindow AppWindow => AppWindow.GetFromWindowId(Win32Interop.GetWindowIdFromWindow(WindowNative.GetWindowHandle(MainWindow)));

    public static App App => Application.Current as App;

    [DllImport("user32.dll", CharSet = CharSet.Auto)]
    public static extern IntPtr SendMessage(IntPtr hWnd, int Msg, int wParam, IntPtr lParam);

    [DllImport("user32.dll")]
    public static extern IntPtr GetActiveWindow();

    public static bool TrySetMicaBackdrop()
    {
        if (!MicaController.IsSupported()) return false; // Mica is not supported on this system
        m_wsdqHelper = new WindowsSystemDispatcherQueueHelper();
        m_wsdqHelper.EnsureWindowsSystemDispatcherQueueController();

        // Hooking up the policy object
        m_configurationSource = new SystemBackdropConfiguration();
        MainWindow.Activated += Window_Activated;
        ((FrameworkElement)MainWindow.Content).ActualThemeChanged += Window_ThemeChanged;

        // Initial configuration state.
        m_configurationSource.IsInputActive = true;
        SetConfigurationSourceTheme();

        m_micaController = new MicaController();

        // Enable the system backdrop.
        // Note: Be sure to have "using WinRT;" to support the Window.As<...>() call.
        m_micaController.AddSystemBackdropTarget(((MainWindow)(Application.Current as App).m_window)
            .As<ICompositionSupportsSystemBackdrop>());
        m_micaController.SetSystemBackdropConfiguration(m_configurationSource);
        return true; // succeeded
    }

    private static void SetConfigurationSourceTheme()
    {
        switch (((FrameworkElement)MainWindow.Content).ActualTheme)
        {
            case ElementTheme.Dark:
                m_configurationSource.Theme = SystemBackdropTheme.Dark;
                break;
            case ElementTheme.Light:
                m_configurationSource.Theme = SystemBackdropTheme.Light;
                break;
            case ElementTheme.Default:
                m_configurationSource.Theme = SystemBackdropTheme.Default;
                break;
        }
    }

    private static void Window_ThemeChanged(FrameworkElement sender, object args)
    {
        if (m_configurationSource != null) SetConfigurationSourceTheme();
    }

    private static void Window_Activated(object sender, WindowActivatedEventArgs args)
    {
        m_configurationSource.IsInputActive = args.WindowActivationState != WindowActivationState.Deactivated;
    }
}

public class WindowsSystemDispatcherQueueHelper
{
    private object _mDispatcherQueueController;

    [DllImport("CoreMessaging.dll")]
    private static extern int CreateDispatcherQueueController([In] DispatcherQueueOptions options,
        [In] [Out] [MarshalAs(UnmanagedType.IUnknown)]
        ref object dispatcherQueueController);

    public void EnsureWindowsSystemDispatcherQueueController()
    {
        if (DispatcherQueue.GetForCurrentThread() != null)
            // one already exists, so we'll just use it.
            return;

        if (_mDispatcherQueueController == null)
        {
            DispatcherQueueOptions options;
            options.dwSize = Marshal.SizeOf(typeof(DispatcherQueueOptions));
            options.threadType = 2; // DQTYPE_THREAD_CURRENT
            options.apartmentType = 2; // DQTAT_COM_STA

            CreateDispatcherQueueController(options, ref _mDispatcherQueueController);
        }
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct DispatcherQueueOptions
    {
        internal int dwSize;
        internal int threadType;
        internal int apartmentType;
    }
}
```
``` csharp
public MainWindow()
    {
        InitializeComponent();
        Activated += (_, _) =>
        {
            UIHelper.AppWindow.Resize(new SizeInt32(UIHelper.GetActualPixel(750), UIHelper.GetActualPixel(800)));
            UIHelper.TrySetMicaBackdrop();
        };
    }
```

The above code borrows the sample code in WinUI 3 Gallery.

**Comment by xiaoli8848** [comment]
I have temporarily solved this problem.
Just set the Mica background in the App's **OnLaunched** event instead of the MainWindow's _OnActivated_ event.
But I guess it might be a bug in this library?

``` csharp
    protected override void OnLaunched(LaunchActivatedEventArgs args)
    {
        m_window = new MainWindow();
        UIHelper.TrySetMicaBackdrop();
        // Resize the window and set the title.
        m_window.Activate();
    }
```

**Comment by HavenDV** [comment]
Hello. Thank you for the detailed description of the problem and its cause. I haven't used Mica in my applications so this looks new to me and I can't see any overlap with the library.
I can say that the winapi call to create TrayIcon occurs on the `Loaded` event for FrameworkElement:
https://github.com/HavenDV/H.NotifyIcon/blob/b618d32bb9ab86eba509edf972764cc328d83b9e/src/libs/H.NotifyIcon.Shared/TaskbarIcon.cs#L48-L58

**Comment by HavenDV** [comment]
I guess it's important here to call Mica initialization before winapi calls to create TrayIcon. But the library is not able to manage this. If you only add a property that explicitly turns off this Loaded handler and you yourself will explicitly create it at the right time.

**Comment by xiaoli8848** [comment]
> I guess it's important here to call Mica initialization before winapi calls to create TrayIcon. But the library is not able to manage this. If I only add a property that explicitly turns off this Loaded handler and you yourself will explicitly create it at the right time.

So maybe TrayIcon is created in or after MainWindow's OnActivated event, Mica or Acrylic material can only be initialized before MainWindow.Activate() is executed?

**Comment by HavenDV** [comment]
Yes, quite, given that this also involves WinApi
But does the method through Activated with Mica work in a normal application, given this code?
<img width="638" alt="image" src="https://user-images.githubusercontent.com/3002068/187160123-380d2bdb-db27-4168-93e2-075d2920ba09.png">

**Comment by xiaoli8848** [comment]
> Yes, quite, given that this also involves WinApi But does the method through Activated with Mica work in a normal application, given this code? <img alt="image" width="638" src="https://user-images.githubusercontent.com/3002068/187160123-380d2bdb-db27-4168-93e2-075d2920ba09.png">

Excuse me, did you mean to use Mica in Win32 programs? I've only used Mica with WinUI 3 because it requires the Windows App SDK.

**Comment by HavenDV** [comment]
> Now I know the reason for this exception. My app calls utility class code on the Activated event to **set the app background to the Mica material**. After I delete the relevant code, the menu will appear normally after right-clicking the tray icon. These are the relevant codes:
> 
> ```cs
> using System.Runtime.InteropServices;
> using Windows.System;
> using Microsoft.UI;
> using Microsoft.UI.Composition;
> using Microsoft.UI.Composition.SystemBackdrops;
> using Microsoft.UI.Windowing;
> using WinRT;
> using WinRT.Interop;
> 
> namespace AutoDL.Utilities;
> 
> public static class UIHelper
> {
>     public const int ICON_BIG = 1;
>     public const int ICON_SMALL = 0;
>     public const int WA_ACTIVE = 0x01;
>     public const int WA_INACTIVE = 0x00;
>     public const int WM_ACTIVATE = 0x0006;
>     public const int WM_SETICON = 0x0080;
> 
>     private static WindowsSystemDispatcherQueueHelper m_wsdqHelper; // See separate sample below for implementation
>     private static MicaController m_micaController;
>     private static SystemBackdropConfiguration m_configurationSource;
> 
>     public static IntPtr MainWindow_Handle = WindowNative.GetWindowHandle(MainWindow);
> 
>     public static WindowId MainWindow_ID = Win32Interop.GetWindowIdFromWindow(MainWindow_Handle);
> 
>     public static MainWindow MainWindow => (MainWindow)(Application.Current as App).m_window;
> 
>     public static AppWindow AppWindow => AppWindow.GetFromWindowId(Win32Interop.GetWindowIdFromWindow(WindowNative.GetWindowHandle(MainWindow)));
> 
>     public static App App => Application.Current as App;
> 
>     [DllImport("user32.dll", CharSet = CharSet.Auto)]
>     public static extern IntPtr SendMessage(IntPtr hWnd, int Msg, int wParam, IntPtr lParam);
> 
>     [DllImport("user32.dll")]
>     public static extern IntPtr GetActiveWindow();
> 
>     public static bool TrySetMicaBackdrop()
>     {
>         if (!MicaController.IsSupported()) return false; // Mica is not supported on this system
>         m_wsdqHelper = new WindowsSystemDispatcherQueueHelper();
>         m_wsdqHelper.EnsureWindowsSystemDispatcherQueueController();
> 
>         // Hooking up the policy object
>         m_configurationSource = new SystemBackdropConfiguration();
>         MainWindow.Activated += Window_Activated;
>         ((FrameworkElement)MainWindow.Content).ActualThemeChanged += Window_ThemeChanged;
> 
>         // Initial configuration state.
>         m_configurationSource.IsInputActive = true;
>         SetConfigurationSourceTheme();
> 
>         m_micaController = new MicaController();
> 
>         // Enable the system backdrop.
>         // Note: Be sure to have "using WinRT;" to support the Window.As<...>() call.
>         m_micaController.AddSystemBackdropTarget(((MainWindow)(Application.Current as App).m_window)
>             .As<ICompositionSupportsSystemBackdrop>());
>         m_micaController.SetSystemBackdropConfiguration(m_configurationSource);
>         return true; // succeeded
>     }
> 
>     private static void SetConfigurationSourceTheme()
>     {
>         switch (((FrameworkElement)MainWindow.Content).ActualTheme)
>         {
>             case ElementTheme.Dark:
>                 m_configurationSource.Theme = SystemBackdropTheme.Dark;
>                 break;
>             case ElementTheme.Light:
>                 m_configurationSource.Theme = SystemBackdropTheme.Light;
>                 break;
>             case ElementTheme.Default:
>                 m_configurationSource.Theme = SystemBackdropTheme.Default;
>                 break;
>         }
>     }
> 
>     private static void Window_ThemeChanged(FrameworkElement sender, object args)
>     {
>         if (m_configurationSource != null) SetConfigurationSourceTheme();
>     }
> 
>     private static void Window_Activated(object sender, WindowActivatedEventArgs args)
>     {
>         m_configurationSource.IsInputActive = args.WindowActivationState != WindowActivationState.Deactivated;
>     }
> }
> 
> public class WindowsSystemDispatcherQueueHelper
> {
>     private object _mDispatcherQueueController;
> 
>     [DllImport("CoreMessaging.dll")]
>     private static extern int CreateDispatcherQueueController([In] DispatcherQueueOptions options,
>         [In] [Out] [MarshalAs(UnmanagedType.IUnknown)]
>         ref object dispatcherQueueController);
> 
>     public void EnsureWindowsSystemDispatcherQueueController()
>     {
>         if (DispatcherQueue.GetForCurrentThread() != null)
>             // one already exists, so we'll just use it.
>             return;
> 
>         if (_mDispatcherQueueController == null)
>         {
>             DispatcherQueueOptions options;
>             options.dwSize = Marshal.SizeOf(typeof(DispatcherQueueOptions));
>             options.threadType = 2; // DQTYPE_THREAD_CURRENT
>             options.apartmentType = 2; // DQTAT_COM_STA
> 
>             CreateDispatcherQueueController(options, ref _mDispatcherQueueController);
>         }
>     }
> 
>     [StructLayout(LayoutKind.Sequential)]
>     private struct DispatcherQueueOptions
>     {
>         internal int dwSize;
>         internal int threadType;
>         internal int apartmentType;
>     }
> }
> ```
> 
> ```cs
> public MainWindow()
>     {
>         InitializeComponent();
>         Activated += (_, _) =>
>         {
>             UIHelper.AppWindow.Resize(new SizeInt32(UIHelper.GetActualPixel(750), UIHelper.GetActualPixel(800)));
>             UIHelper.TrySetMicaBackdrop();
>         };
>     }
> ```
> 
> The above code borrows the sample code in WinUI 3 Gallery.

I mean your code from this message

**Comment by xiaoli8848** [comment]
According to [Microsoft Docs page](https://docs.microsoft.com/windows/apps/desktop/modernize/apply-mica-win32), using Mica material requires Microsoft.WindowsAppSDK NuGet Package. This is more troublesome on non-WinUI projects that are not packaged.
