### ISSUE TITLE
GeneratedIconText not found

### ISSUE THREAD

**Issue by SinanAkkoyun** [HavenDV/H.NotifyIcon#38]
### Describe the bug

Hi, I am using the WinUI version and I am SUPER new to Windows Desktop App development.

It says "GeneratedIconText was not found in type TaskbarIcon"
Is that feature not supported on your WinUI version?

Thanks for helping!

### Steps to reproduce the bug

Install latest WinUI package

### Platform

WinUI

### IDE

Visual Studio 2022

### Windows Version

Windows 11

### WindowsAppSDK Version

1.0

### WindowsAppSDK Type

Packaged

### Manifest

Default

**Comment by HavenDV** [comment]
Sorry, I forgot to edit the README to reflect the latest changes. Here is an example
```xml
        <tb:TaskbarIcon.GeneratedIcon> 
             <tb:GeneratedIcon 
                 Text="❤️" 
                 Foreground="Red" 
                 /> 
         </tb:TaskbarIcon.GeneratedIcon>
```

**Comment by SinanAkkoyun** [comment]
Thank you so so much!
And wow thanks for the quick response!

**Comment by HavenDV** [comment]
I also updated the README
