### ISSUE TITLE
Change IconSource to allow drawn images

### ISSUE THREAD

**Issue by tmr0861** [HavenDV/H.NotifyIcon#4]
I have an app that changes the icon based on dynamic data.  I also let the user change background and text color and text size.  I draw the image as a drawing visual and just want to use that as the IconSource using databinding.  

I was able to accomplish this by changing your IconSource dependency property to a BitmapSource type and adding a ToIcon extension method for that type.  I save my drawing visual as a BitmapImage and bind the IconSource to this property and it works like a charm.

**Comment by HavenDV** [comment]
Hi. Can you provide your extension method?

**Comment by tmr0861** [comment]
This may not be the best way to do it, but it seems to work.  Might have memory leaks:

```
        public static Icon ToIcon(this BitmapSource bitmap)
        {
            var enc = new BmpBitmapEncoder();
            enc.Frames.Add(BitmapFrame.Create(bitmap));

            using var stream = new MemoryStream();
            enc.Save(stream);

            using var bmp = new Bitmap(stream);
            using var icon = Icon.FromHandle(bmp.GetHicon());
            return icon;
        }

```

**Comment by HavenDV** [comment]
Can I partially use [your code](https://github.com/tmr0861/WeekNotifier) to create an example of dynamic icon generation? And simplifying this process by moving the code to the side of the library.

**Comment by HavenDV** [comment]
> This may not be the best way to do it, but it seems to work. Might have memory leaks:
> 
> ```
>         public static Icon ToIcon(this BitmapSource bitmap)
>         {
>             var enc = new BmpBitmapEncoder();
>             enc.Frames.Add(BitmapFrame.Create(bitmap));
> 
>             using var stream = new MemoryStream();
>             enc.Save(stream);
> 
>             using var bmp = new Bitmap(stream);
>             using var icon = Icon.FromHandle(bmp.GetHicon());
>             return icon;
>         }
> ```

Thanks for the example. I tried and converting from System.Drawing.Bitmap to System.Drawing.Icon this way removes transparency from icons, so I found another option (convert PNG bytes received from encoder to ICO format and create Icon from them)

**Comment by HavenDV** [comment]
At the moment I have changed the `TaskbarIcon.Icon` property to a Dependency Property, so I see the best way for your task is to just directly bind to the CurrentIcon (using your application example) without any additional transformations

**Comment by HavenDV** [comment]
I added ability to generate icons. There are some examples: https://github.com/HavenDV/H.NotifyIcon#generated-icons
