### ISSUE TITLE
Exception when attempting to show window after closing it via title bar

### ISSUE THREAD

**Issue by paazca** [HavenDV/H.NotifyIcon#54]
### Describe the bug

When running H.NotifyIcon.Apps.WinUI, after closing the window via the X icon in the title bar, attempting to show the window via the taskbar icon results in an exception.

Specifically, `System.Runtime.InteropServices.COMException: 'The operation identifier is not valid. (0x800710DD)'` when accessing `window.Visible` in `ShowHideWindowCommand_ExecuteRequested`.

### Steps to reproduce the bug

1. Run H.NotifyIcon.Apps.WinUI
2. Close the window via the title bar X icon
3. Left click the taskbar icon or right click and select "show/hide window"
4. Exception occurs

### Expected behavior

The window should appear.

### Screenshots

![image](https://user-images.githubusercontent.com/31186542/206455030-2a4ff0f1-151f-4b83-bff2-21fab37e52f2.png)

### Platform

WinUI

### IDE

Visual Studio 2022

### Windows Version

Windows 11

### WindowsAppSDK Version

1.2

### WindowsAppSDK Type

Packaged

**Comment by JasonWei512** [comment]
Use a [DispatcherQueue](https://learn.microsoft.com/en-us/uwp/api/windows.system.dispatcherqueue) to execute UI related code on the main UI thread.

**Comment by dreammaster38** [comment]
Hi JasonWei512,

thank you for your feedback. I will try this. 

Nevertheless i found another solution. I hooked up the Closing-Event of the MainWindow and show a confirmation-dialog if the user want's to close to tray or exit the application. On close to tray i just cancel the closing event and do a window.Hide() on exit I do an App.Exit().

**Comment by myfix16** [comment]
> Hi JasonWei512,
> 
> thank you for your feedback. I will try this.
> 
> Nevertheless i found another solution. I hooked up the Closing-Event of the MainWindow and show a confirmation-dialog if the user want's to close to tray or exit the application. On close to tray i just cancel the closing event and do a window.Hide() on exit I do an App.Exit().

Hi dreammaster38, 

What event did you hook and how did you cancel the closing event? I tried to hook the `MainWindow.Closed` event but I didn't find a way to cancel it. Would you like to share relevant code snippets?

**Comment by JasonWei512** [comment]
@myfix16 
``` csharp
MainWindow.Closed += MainWindow_Closed;

private void MainWindow_Closed(object sender, WindowEventArgs args)
{
    args.Handled = true;
}
```

**Comment by myfix16** [comment]
Resolved, thank you @JasonWei512 !
