### ISSUE TITLE
TrayIcon create failed after change executable file path with PublishSingleFile

### ISSUE THREAD

**Issue by MrBaoquan** [HavenDV/H.NotifyIcon#69]
### Describe the bug

i am build app from wpf with "PublishSingleFile", after build to a single file, everything is right now. but if i copy the executeable file to another path, TrayIcon will be created failed and find nothing in the NotifyBar

### Steps to reproduce the bug

1. build a wpf app with PublishSingleFile
2. run the app
3. move app to another path
4. run the app, TrayIcon will not be created now

### Platform

WPF

### IDE

Visual Studio 2022

### Windows Version

Windows 10

### WindowsAppSDK Type

None

**Comment by MRoc** [comment]
I think it's related to the fact that the GUID can't be properly created for the tray icon in case `PublishSingleFile` is turned on. There are two traces:

1. `TrayIcon.Id` states `Windows associates a Guid with the path of the binary, so you must use the new Guid when you change the path`.
2. Some APIs around paths don't work when having `PublishSingleFile=true`, see https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli#api-incompatibility.

This **hack** made it work for me, setting some random GUID through reflection:

```
_notifyIcon = (TaskbarIcon)(FindResource("TrayIcon") ?? throw new InvalidOperationException("No TrayIcon found!"));

var propTrayIcon = _notifyIcon.GetType().GetProperty("TrayIcon", BindingFlags.NonPublic | BindingFlags.Instance);
var trayIcon = (TrayIcon)propTrayIcon.GetValue(_notifyIcon);

var propId = trayIcon.GetType().GetProperty("Id", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
propId.SetValue(trayIcon, Guid.NewGuid());

_notifyIcon.ForceCreate();
```

**Comment by HavenDV** [comment]
Generating a random GUID on every run has its own issues, I've already tried that.
At the moment, TrayIcon uses the EntryAssembly.Location hash to generate the same GUID for the same path
https://github.com/HavenDV/H.NotifyIcon/blob/9a83ca20429222dda82d83e17e815d05fcef290e/src/libs/H.NotifyIcon/Core/TrayIcon.cs#L147-L181
I guess the problem is either in the EntryAssembly definition or its Location when using PublishSingleFile

**Comment by MRoc** [comment]
With `PublishSingleFile=true`, for me, `Assembly.GetEntryAssembly()` did not work as expected. I replaced it by `Process.GetCurrentProcess().MainModule?.FileName`.

**Comment by djuchems** [comment]
GetEntryAssembly() doesn't work for single file deployments, because the "EntryAssembly" does not exist physically at this moment. `AppContext.BaseDirectory` might be the alternative.

**Comment by HavenDV** [comment]
Please check `Environment.ProcessPath`

**Comment by djuchems** [comment]
'AppContext.BaseDirectory' works as well as 'Environment.ProcessPath'

This is a workaround (after InitializeComponent()):
trayIcon.Id = TrayIcon.CreateUniqueGuidFromString($"{Environment.ProcessPath}_{null}");

But this should be set "earlier", because now I have two Icons, the one that disappears and that one that works.

**Comment by HavenDV** [comment]
> With PublishSingleFile=true, for me, Assembly.GetEntryAssembly() did not work as expected. I replaced it by Process.GetCurrentProcess().MainModule?.FileName.

@MRoc Can you please tell more what happened with Assembly.GetEntryAssembly() for PublishSingleFile? Was it returning null, throwing an exception, or was Assembly.Location returning null, or throwing an exception?
I will be using `Environment.ProcessPath` but this is only available for net6.0 and above. Using `Process.GetCurrentProcess().MainModule?.FileName` also has its [downsides](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1839). So I would like to use it only if `Environment.ProcessPath` and EntryAssembly are not available.

**Comment by MRoc** [comment]
My experiments revealed that `Assembly.GetEntryAssembly().Location` returns empty string `""` if `PublishSingleFile=true`.

**Comment by HavenDV** [comment]
Please test latest version from NuGet

**Comment by MrBaoquan** [comment]
> Please test latest version from NuGet

Problem is resolved, grateful thanks
