### ISSUE TITLE
Trayicon disappears at mouseover

### ISSUE THREAD

**Issue by djuchems** [HavenDV/H.NotifyIcon#71]
Greetings,

I've created an simple implementation of the NotifyIcon Control:
`<tb:TaskbarIcon ToolTipText="AppName" Name="trayIcon" IconSource="/Images/appicon.ico" TrayMouseDoubleClick="TaskbarIcon_TrayMouseDoubleClick" />`

Running in "Debug" mode everything is fine, but when I deploy the application in "Release" configuration, **the Trayicon disappears when I move the mouse over it**.
Visual Studio 2022 with .net 6.0 - single file deploy, default Release configuration.

What happens there and how can I fix it?

Thanks in advance,
Denis

**Comment by HavenDV** [comment]
I think this is related to #69

**Comment by HavenDV** [comment]
Please check latest version from NuGet

**Comment by djuchems** [comment]
Works perfect now. Many thanks!
