### ISSUE TITLE
[WinUI] MenuFlyout width error on the first time popup

### ISSUE THREAD

**Issue by emako** [HavenDV/H.NotifyIcon#73]
### Describe the bug

```c#
        <notifyIcon:TaskbarIcon
            x:Name="TaskbarIconApp"
            DoubleClickCommand="{x:Bind ViewModel.ActiveOrHideAppCommand}"
            MenuActivation="RightClick"
            NoLeftClickDelay="True"
            IconSource="{x:Bind base:Pack.UriIcon}"
            ContextMenuMode="SecondWindow">
            <notifyIcon:TaskbarIcon.ContextFlyout>
                <MenuFlyout Placement="RightEdgeAlignedTop" AreOpenCloseAnimationsEnabled="False">
                    <MenuFlyoutItem Width="180" MaxWidth="180" Text="显示／隐藏" Command="{x:Bind ViewModel.ActiveOrHideAppCommand}" />
                    <MenuFlyoutSeparator/>
                    <MenuFlyoutItem Width="180" MaxWidth="180" Text="退出" Icon="Cancel" Command="{x:Bind ViewModel.ExitAppCommand}" />
                </MenuFlyout>
            </notifyIcon:TaskbarIcon.ContextFlyout>
        </notifyIcon:TaskbarIcon>
```

### Screenshots

first time popup -> Error width
![image](https://user-images.githubusercontent.com/24737061/217332978-0650e981-f9fa-4d57-9e66-53358d23b956.png)

second time popup -> allright
![image](https://user-images.githubusercontent.com/24737061/217333524-0179f73d-eddf-47a1-94c2-25fe7780d62f.png)

How can I handle for fixed width?

### NuGet package version

<PackageReference Include="H.NotifyIcon.WinUI" Version="2.0.77" />

### IDE

Visual Studio 2022

### Windows Version

Windows 11

### WindowsAppSDK Version

1.1

### WindowsAppSDK Type

Packaged

**Comment by kqakqakqa** [comment]
This also happens to me, on first time popup when `MenuFlyoutItem` has an icon

![image](https://github.com/HavenDV/H.NotifyIcon/assets/58761476/fb6a73bf-01d5-4e29-aa25-ccdb746ce66d)

![image](https://github.com/HavenDV/H.NotifyIcon/assets/58761476/fb8c929a-d6b4-4374-ad03-1596ac0d4d8e)

``` xaml
<tb:TaskbarIcon ContextMenuMode="SecondWindow" NoLeftClickDelay="True">
    <tb:TaskbarIcon.ContextFlyout>
        <MenuFlyout AreOpenCloseAnimationsEnabled="False">

            <MenuFlyoutItem Icon="Sync" Text="Refresh"/>
            <MenuFlyoutSeparator />
            <MenuFlyoutItem Text="Exit1234567890"/>
            
        </MenuFlyout>
    </tb:TaskbarIcon.ContextFlyout>
</tb:TaskbarIcon>
```

**Comment by HavenDV** [comment]
As far as I remember, I'm currently not taking icons into account when calculating the initial width, so that's a good point.
There is a bug in WinUI with different widths during the first display and after, which we are trying to adapt to so that there is no difference, and they are not going to fix it
