### ISSUE TITLE
[WinUI] GeneratedIcon not shown on the task bar

### ISSUE THREAD

**Issue by myfix16** [HavenDV/H.NotifyIcon#75]
### Describe the bug

In my Windows App SDK 1.2 application, I used `GeneratedIcon` with the following code:
```
<tb:TaskbarIcon.GeneratedIcon>
        <tb:GeneratedIcon
            Text="99"
            Foreground="White"
            FontWeight="SemiBold"
            FontFamily="Arial"
        />
</tb:TaskbarIcon.GeneratedIcon>
```
However, the icon is not displayed on the task bar.
![image](https://user-images.githubusercontent.com/61649477/219846852-8ffe885f-70ed-428b-8628-0afbe45585d8.png)

I added `FontSize="40`, and the icon appeared. However, other sizes, such as 55 or the default value, failed to show up.

I'm using Windows 11 beta build 22623.1325. The application works normal in previous Windows versions and seems to break in recent beta versions.

### Steps to reproduce the bug

1. Create an empty Windows App SDK 1.2 packaged app
2. Add an tray icon using the code I posted above
3. Run and observe the behavior

### Expected behavior

The GeneratedIcon should display normally.

### Platform

WinUI

### IDE

Visual Studio 2022

### Windows Version

Windows 11

### WindowsAppSDK Version

Other

### WindowsAppSDK Type

Packaged

**Comment by HavenDV** [comment]
I'm not sure if it's worth spending time on this now, because everything can change in the next beta versions.
In addition, I have plans to transfer drawing from System.Drawing to SkiaSharp/Microsoft.Maui.Graphics, perhaps this would get rid of bugs
https://github.com/HavenDV/H.NotifyIcon/issues/45

**Comment by myfix16** [comment]
Year, I see that. Hope SkiaSharp/Microsoft.Maui.Graphics would solve the problem.
