### ISSUE TITLE
PopupMenuSeparator is missing when PublishTrimmed is true.

### ISSUE THREAD

**Issue by l619534951** [HavenDV/H.NotifyIcon#86]
### Describe the bug

**PublishTrimmed is false**
![false](https://user-images.githubusercontent.com/17621099/229180562-63063835-95b5-4aa3-bdbf-be8663b621a9.png)

**PublishTrimmed is true**
![true](https://user-images.githubusercontent.com/17621099/229180587-4ed685e5-21ae-4fa0-9a7e-d55b2467ff8a.png)

### Platform

WinUI

### IDE

Visual Studio 2022

### Windows Version

Windows 11

### WindowsAppSDK Version

Other

### WindowsAppSDK Type

Unpackaged

### Additional context

[PopupMenuSeparatorMissingDemo.zip](https://github.com/HavenDV/H.NotifyIcon/files/11124144/PopupMenuSeparatorMissingDemo.zip)

**Comment by HavenDV** [comment]
Thank you very much. Cute cat :)
