### ISSUE TITLE
VS 2022 Windows 11 Dev Environment Setup

### ISSUE THREAD

**Issue by Tide** [HavenDV/H.NotifyIcon#9]
I am using Windows 11 and VS 2022 as my dev environment.  In order to get this solution going I have to do a couple of things.  I thought I would post those here.  I am not sure if you need to change anything or if others just need to do this if they have my issues.   You will know better on that than I do.  

1.  In this machine the Visual Studio Installer lists the lowest SDK you can install as 4.6.1.  I had to go get 4.5.1 SDK manually.

2.  When trying to debug H.NotifyIcon.Apps.WinUI I get an error of Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies.  To solve this I created a launchSettings.json in the Properties folder as per this article https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/single-project-msix?tabs=csharp.  I am just a hobbyist so I can only say this works for me.  Hopefully, it is right.

Here are the contents of launchSettings.json :

```json
{
  "profiles": {
    "H.NotifyIcon.Apps.WinUI (Package)": {
      "commandName": "MsixPackage"
    },
    "H.NotifyIcon.Apps.WinUI (Unpackaged)": {
      "commandName": "Project"
    }
  }
}
```

**Comment by HavenDV** [comment]
> 2\. When trying to debug H.NotifyIcon.Apps.WinUI I get an error of Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies.  To solve this I created a launchSettings.json in the Properties folder as per this article https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/single-project-msix?tabs=csharp.  I am just a hobbyist so I can only say this works for me.  Hopefully, it is right.

Yes, you are right, there was an outdated .gitignore here, which did not allow downloading these files (they were in the local version)

> 1. In this machine the Visual Studio Installer lists the lowest SDK you can install as 4.6.1.  I am guessing I could go get the 4.5.1 SDK and maybe/probably it would install and be fine.  I chose to upgrade H.NotifyIcon.Wpf.csproj and H.NotifyIcon.csproj to 4.6.1. I am not sure if this is going to cause any issues.  It does let me build the solution but no testing has been done.  I am having issues that I want to start testing so I will have to address this before then.

Thanks, I've added a link to the documentation so people don't have similar problems
> The minimum supported version of the .Net Framework is 4.5.1.  
> So in some cases to build the project you will need to install this -  
> https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net451-developer-pack-offline-installer

**Comment by Tide** [comment]
On to testing and thanks.
