### ISSUE TITLE
MICA material is not showing after closing window and opening from tray icon [WinUI3]

### ISSUE THREAD

**Issue by insomniachi** [HavenDV/H.NotifyIcon#93]
### Describe the bug

i have the following code
```
        MainWindow.Closed += (sender, args) =>
        {
            if (HandleClosedEvents)
            {
                args.Handled = true;
                MainWindow.Hide();
            }
        };
```
```
        <tb:TaskbarIcon
            x:Name="TrayIcon"
            x:FieldModifier="public"
            ContextMenuMode="SecondWindow"
            IconSource="/Assets/WindowIcon.ico"
            LeftClickCommand="{x:Bind ShowHideWindowCommand}"
            NoLeftClickDelay="True"
            ToolTipText="ToolTip">
            <tb:TaskbarIcon.ContextFlyout>
                <MenuFlyout AreOpenCloseAnimationsEnabled="False">
                    <MenuFlyoutItem Command="{x:Bind ShowHideWindowCommand}" Text="Show/Hide Window" />
                    <MenuFlyoutSeparator />
                    <MenuFlyoutItem Command="{x:Bind ExitApplicationCommand}" Text="Exit" />
                </MenuFlyout>
            </tb:TaskbarIcon.ContextFlyout>
        </tb:TaskbarIcon>
```
commands are copied from WinUI samples in this repo.

when app opens mica is rendered
![image](https://github.com/HavenDV/H.NotifyIcon/assets/6525704/39442aee-f14a-4436-bbde-55787bd2670d)
when i close app with close button, then click the tray icon, the window comes back, but mica is not there
![image](https://github.com/HavenDV/H.NotifyIcon/assets/6525704/22285da0-830c-48d3-8952-1371ce0720c7)

if i just click tray icon, without closing window, there is no issue with mica.
i'm using WinUIEx window (https://github.com/dotMorten/WinUIEx)

### NuGet package version

H.NotifyIcon.WinUI 2.0.108

### Platform

WinUI

### IDE

Visual Studio 2022

### Windows Version

Windows 11

### WindowsAppSDK Version

Other

### WindowsAppSDK Type

Unpackaged

**Comment by edoust** [comment]
I don't have that issue, how do you control MICA?

**Comment by insomniachi** [comment]
it works now
