### ISSUE TITLE
Only Create One Context Menu for many Instances of WinUI 3 Packaged App

### ISSUE THREAD

**Issue by Jack251970** [HavenDV/H.NotifyIcon#99]
### Describe the bug

I enjoy using your context menu all the time, but when I create a new instance of an application and then quit it, and the context menu icon related to old version of the same application will disappear.
My application is based on the template from WinUI Template Studio. This is the function of "App", and I show the instance of one window here.
```
public App()
{
    if (SystemHelper.IsWindowExist(null, "AppDisplayName". GetLocalized()))
    {
        Current.Exit();
    }

   // ...
}
```
And IsWindowExist funtion is:
```
/// <summary>
    /// Check if window exists and show window.
    /// </summary>
    [DllImport("user32.dll", EntryPoint = "FindWindow", CharSet = CharSet.Unicode)]
    private static extern IntPtr FindWindow(string? lpClassName, string? lpWindowName);
    [DllImport("user32.dll")]
    private static extern bool ShowWindow(IntPtr hwnd, int nCmdShow);
    [DllImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static extern bool SetForegroundWindow(IntPtr hWnd);
    [DllImport("user32.dll")]
    public static extern IntPtr SendMessage(IntPtr hWnd, uint msg, int wParam, int lParam);
    public static bool IsWindowExist(string? className, string? windowName)
    {
        var handle = FindWindow(className, windowName);
        return handle != IntPtr.Zero;
    }
```

This is the TrayMenuControl:
``` xaml
<UserControl
    xmlns:tb="using:H.NotifyIcon">
    <UserControl.Resources>
        <XamlUICommand x:Key="ShowCommand" x:Uid="TrayIcon_Show" ExecuteRequested="ShowWindow" >
            <XamlUICommand.IconSource>
                <SymbolIconSource Symbol="OpenPane"/>
            </XamlUICommand.IconSource>
        </XamlUICommand>
        <MenuFlyout x:Key="TrayContextFlyout" AreOpenCloseAnimationsEnabled="False">
            <MenuFlyoutItem Command="{StaticResource ShowCommand}"/>
        </MenuFlyout>
    </UserControl.Resources>
    <tb:TaskbarIcon
        ToolTipText="Time Manager 3"
        IconSource="/Assets/WindowIcon.ico"
        ContextFlyout="{StaticResource TrayContextFlyout}"
        MenuActivation="RightClick"/>
</UserControl>
```
``` c
public sealed partial class TrayMenuControl : UserControl
{
    public TrayMenuControl()
    {
        InitializeComponent();
    }

    private void ShowWindow(XamlUICommand sender, ExecuteRequestedEventArgs args)
    {
        App.ShowMainWindow(false);
    }
}
```
And I register the context menu in ShellPage:
```
<control:TrayMenuControl/>
```

### NuGet package version

H.NotifyIcon.WinUI 2.0.108

### Platform

WinUI

### IDE

Visual Studio 2022

### Windows Version

Windows 10

### WindowsAppSDK Version

Other

### WindowsAppSDK Type

Packaged

**Comment by Jack251970** [comment]
In detail, I find that for the app of MSIX package, opening many instances of one application will only create one context menu?!

![image](https://github.com/HavenDV/H.NotifyIcon/assets/53996452/7ccaac47-74e5-41a6-bc9a-b71f499b9c09)
 As you can see here, I open this app twice, but I only have one context menu?

**Comment by HavenDV** [comment]
By default, the unique GUID generation strategy does not include support for the ability to run the same application multiple times (the same GUID will be generated for the same application name). This is necessary for a number of factors and you can read about it in the Microsoft documentation. https://github.com/HavenDV/H.NotifyIcon#behavior-that-needs-attention
You can set the TaskbarIcon.CustomName property to get around this

**Comment by Jack251970** [comment]
Year, I have to use way to ensure that only one instance will be created. Thanks for your reply.
